### PR TITLE
Remove autotools buildsystem

### PR DESCRIPTION
**Pull request by jbkempf**

### CODE REVIEW

**Comment by davilla** [comment]
reason ?

**Comment by jbkempf** [comment]
> reason ?

Because we have meson now, to replace it.

**Comment by davilla** [comment]
ok, I guess upstream consumers will now have to handle meson as well as autotools and cmake.

**Comment by jbkempf** [comment]
> ok, I guess upstream consumers will now have to handle meson as well as autotools and cmake.

Is that an issue? A lot of people and projects are moving to meson, since autotools in unmaintained.

**Comment by davilla** [comment]
GNU stopped maintaining autotools ? News to me.

**Comment by jbkempf** [comment]
> GNU stopped maintaining autotools ? News to me.

It shouldn't be a news. Autoconf has not seen a release in 8 years now... Libtool since 5 years...

**Comment by davilla** [comment]
Interesting, but I guess I only worry about tools when they stop working or have to be patched too much. 8 years and still working is impressive.

**Pull request merged**
