### PR TITLE
add SMB files and folders delete

### PR DESCRIPTION
**Pull request by sylverb**
This commit adds files delete function and folders delete function.
These functions returns NT_STATUS_SUCCESS (0) if everything was OK, else way it'll return a NT_STATUS_* error code for protocol errors or a DSM_ERROR_* for "libDSM" errors

### CODE REVIEW

**Comment by sylverb** [comment]
2nd version, feel free to comment or to merge ;)

**Comment by jbkempf** [comment]
assert(s != NULL && tid != -1);

Are you sure you need to assert here?
The tid can never be -1?

**Comment by jbkempf** [comment]
Once again, assert are for code that should be IMPOSSIBLE to reach. Not for misbehaving or malforming inputs.

**Comment by sylverb** [comment]
I just wanted to keep assert fenzy that is already present in the code ! If it is not needed to keep this, I'll remove these asserts with pleasure !

**Comment by fkuehne** [comment]
Yep, and please just replace them with reasonable sanity checks. Will happily merge then :+1:

**Comment by sylverb** [comment]
@jbkempf "The tid can never be -1?"
It can be -1, smb_tree_connect function will return -1 instead of tid value in case of error (see my previous patch), but we have to control against this value as if the application is getting tid value without controlling its validity, it will send requests with a tid of -1 !

**Pull request closed without merging**
