### PR TITLE
File write

### PR DESCRIPTION
**Pull request by sylverb**
This adds the file write feature.
Just open the file as RW instead of RO and use the fwrite function.
You can also use the fseek function to append data to an existing file.

### CODE REVIEW

**Comment by jbkempf** [comment]
Seems nice :)

**Comment by sylverb** [comment]
:)

**Comment by fkuehne** [comment]
Looks good :)

Now off to copy & move! :dancers:

**Comment by jbkempf** [comment]
Maybe delete full directory first, I'd say...

**Comment by sylverb** [comment]
@fkuehne I keep this for next year :p
@jbkempf I don't think that full folder delete should be handled in the library ! There is no SMB command for that, it means that to delete folders we have to enumerate each files inside the folder (recursively to handles folders in folders) and delete each files one by one before being allowed to delete the folder. IMO it should be done by the main application using the library !

**Comment by jbkempf** [comment]
Why not help the application with a helper doing that?

**Pull request merged**
