### PR TITLE
implement TRANS2_FIND_NEXT2 to handle directories with many files (3rd version)

### PR DESCRIPTION
**Pull request by sylverb**
:)

### CODE REVIEW

**Comment by jbkempf** [comment]
Merged :)

**Comment by txia2015** [comment]
sylverb , this is great! Are there some sample codes to use this new interface. Thanks.

**Comment by txia2015** [comment]
sylverb , please forget my last message, I know how to do it now.Thanks.

**Comment by sylverb** [comment]
Yes there is nothing to do, just call smb_find as previously and the function will handle find_next requests if needed ;)

**Pull request closed without merging**
